spring:
#  config:
#    activate:
#      on-profile: test # ???? ??

  datasource:
    url: jdbc:h2:tcp://localhost/~/sbb-mission
    username: sa
    password:
    h2:
      console:
        enabled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    show-sql: true
  output:
    ansi:
      enabled: always
