name: work-1
on:
  push: 
    branches:
      - main
jobs:
  hello1:
    runs-on: ubuntu-latest
    steps:
      - name: sayHi
        run: echo "Hi"
      - name: sayMyName
        run: echo "${{ github.actor }}"
      - uses: actions/checkout@v4 # 소스코드 pull 
      - uses: mathieudutour/github-tag-action@v6.1 #태그를 만들어준다 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
